### ISSUE TITLE
DeprecationWarning: Invalid 'main' field in '/Users/cjm/repos/obographviz/node_modules/node-getopt/package.json' of './lib'. Please either fix that or report it to the module author

### ISSUE THREAD

**Issue by cmungall** [INCATools/obographviz#16]
let's modernize the repo the repo layout

**Comment by pkalita-lbl** [comment]
I can work on this. A few things I think would help modernize this project:
* Replace node-getopt (the immediate cause of the `DeprecationWarning` and which hasn't been updated in 4 years 😮) with [commander](https://www.npmjs.com/package/commander).
* Gulp isn't really doing a lot in this project, and I think using [npm scripts](https://docs.npmjs.com/cli/v8/using-npm/scripts) would be more standard.
* Introduce a build tool like rollup or esbuild, which will allow the library to be developed using TypeScript and the latest language features in development while producing build artifacts that are compatible with older environments.
* Use the `package.json` [`bin` field ](https://docs.npmjs.com/cli/v8/configuring-npm/package-json#bin) to make it easier to run `og2dot` from the command line.
