### ISSUE TITLE
Fix travis build

### ISSUE THREAD

**Issue by cmungall** [INCATools/obographviz#3]
`make test` works on my machine, but not on travis.

I believe I just copied the gulpfile from on of @kltm's projects, many years ago, no idea what current state of the art if for boilerplate test setup for npm, cc @kltm @kshefchek @putmantime @lpalbou

**Comment by kltm** [comment]
For current state-of-the-art, you probably don't want to get involved with some of my older gulpfiles--they were made to deal with history and a certain build profile that may not apply.

**Comment by pkalita-lbl** [comment]
Travis integration was removed in `v0.4.0` in favor of running tests via GitHub Actions. The tests are currently passing in the GitHub Actions run.
