### ISSUE TITLE
Generate Mermaid diagrams

### ISSUE THREAD

**Issue by cthoyt** [INCATools/obographviz#33]
Mermaid is now nicely embeddable in github flavored markdown. The charts generated in this repo could also be formatted that way for easy inclusion in documentation and may also be possible to embed in Jupyter notebooks

docs: https://mermaid.js.org/syntax/stateDiagram.html

cc @caufieldjh

This issue might also directly belong in OAK. feel free to close/transfer it if that's the case

**Comment by matentzn** [comment]
Wrong issue title but possible duplicate of https://github.com/INCATools/obographviz/issues/20

**Comment by cthoyt** [comment]
woah this is great! sorry i am scrambling to put my brain back together. This is a duplicate of #20.
